# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-rnaseq-AZ_fork_0.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages, sorting now alphabetically, without the channel prefix!
  - matplotlib=3.2.1        # Current 3.1.0 build incompatible with multiqc=1.7
  - r-base=3.6.2
  - conda-forge::r-data.table=1.12.8
  - conda-forge::r-gplots=3.0.3
  - conda-forge::r-markdown=1.1

  ## bioconda packages, see above
  - bioconductor-dupradar=1.16.0
  - bioconductor-edger=3.28.0
  - bioconductor-tximeta=1.4.3
  - bioconductor-summarizedexperiment=1.16.0
  - deeptools=3.4.3
  - fastqc=0.11.9
  - gffread=0.11.7
  - hisat2=2.2.0
  - multiqc=1.7
  - picard=2.22.3
  - preseq=2.0.3
  - qualimap=2.2.2d
  - rseqc=3.0.1
  - salmon=1.2.0
  - samtools=1.10
  - sortmerna=4.2.0 # for metatranscriptomics
  - star=2.7.3a          # Don't upgrade me - 2.7X indices incompatible with iGenomes.
  - stringtie=2.1.1
  - subread=2.0.0
  - trim-galore=0.6.5
